{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nice.kotlins",
    "module": "kotson",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "kotson-1.0.0.jar",
          "url": "kotson-1.0.0.jar",
          "size": 214692,
          "sha512": "99f34e81c77b040dc15c59b86682ae488d88538a3888ff220ac3c78290f353d43101998704246a5de56b9e965f964504d95bafb3a06f141c5069c2465e384f71",
          "sha256": "740312a282d463198ba9446d4187119416e71100dfc6a569a86a532276ed561d",
          "sha1": "b7bc447f28c573b51bdd5929076712b08cb6294d",
          "md5": "443d9de95d057ddacabc896e6a776ec3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "kotson-1.0.0.jar",
          "url": "kotson-1.0.0.jar",
          "size": 214692,
          "sha512": "99f34e81c77b040dc15c59b86682ae488d88538a3888ff220ac3c78290f353d43101998704246a5de56b9e965f964504d95bafb3a06f141c5069c2465e384f71",
          "sha256": "740312a282d463198ba9446d4187119416e71100dfc6a569a86a532276ed561d",
          "sha1": "b7bc447f28c573b51bdd5929076712b08cb6294d",
          "md5": "443d9de95d057ddacabc896e6a776ec3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotson-1.0.0-sources.jar",
          "url": "kotson-1.0.0-sources.jar",
          "size": 7842,
          "sha512": "e36d982e1a21bf6f9094e0dfe7280ef5e3a0b8120df9fac2f47ab1634aee05f6c41773adb34372ca0d661c275f7e467106f911a075b652bd188f0f74ebdeaffb",
          "sha256": "58a81a8367ee28b35d04849ce61761f5fd66065f7e50f6f560309a575130c6e9",
          "sha1": "9b0eb841a249f82362fda3ac9d1f82b6d1cb49e8",
          "md5": "2fe28fcd20d9c527fdb9e8eea038db52"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotson-1.0.0-javadoc.jar",
          "url": "kotson-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "27072803c1ed31f97da45c5cdb74ba0041f37335c2ae327003695bcd66b4a4a2538ca12ab38d50360f595e5acfb66f4fea3b01648ab22c37c6417c2394fa1ced",
          "sha256": "58bdd7cbe6813b7cc87d2bcbd09945f1c6df1482695e2e9f2d7d8cab7746f4af",
          "sha1": "3cc864bb519b681c816c3bc2eeec84a955eaaf41",
          "md5": "a65acb131d3e3a501d70e6477486ad30"
        }
      ]
    }
  ]
}
