{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nice.kotlins",
    "module": "kotson",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "kotson-1.0.0.jar",
          "url": "kotson-1.0.0.jar",
          "size": 214692,
          "sha512": "589ab0cecf26bfe5b458f00269163305800b0e0d8dbcac73138377fbe28c65d773162eca62a430cdb4b6c9f1ec80f3bfe5dac9e254b7f39bb07ae29e34b7b9c7",
          "sha256": "acf3029b694f14dbb09c1074338d23cab9204d3d87927dde939359bf4407cbf3",
          "sha1": "d7a9a0218d043d38bf12931d0ea45c3ef4d4b698",
          "md5": "7fe88cda0885fd9045bf5bc0a63b5acd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "kotson-1.0.0.jar",
          "url": "kotson-1.0.0.jar",
          "size": 214692,
          "sha512": "589ab0cecf26bfe5b458f00269163305800b0e0d8dbcac73138377fbe28c65d773162eca62a430cdb4b6c9f1ec80f3bfe5dac9e254b7f39bb07ae29e34b7b9c7",
          "sha256": "acf3029b694f14dbb09c1074338d23cab9204d3d87927dde939359bf4407cbf3",
          "sha1": "d7a9a0218d043d38bf12931d0ea45c3ef4d4b698",
          "md5": "7fe88cda0885fd9045bf5bc0a63b5acd"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotson-1.0.0-sources.jar",
          "url": "kotson-1.0.0-sources.jar",
          "size": 7902,
          "sha512": "faa1d654382f9401cfe24af80582ea15b13d9005f75a8f39546ffa6158cd0d425385a8ad4c19eeabd76a9a3a5e4ad14e5b69a9fef31aa0d066423fbc6f69bf1c",
          "sha256": "94bdb08cdf3a82b82483a04d0fff73f0c9ad605ed4ac5d6878b2d5e390119b89",
          "sha1": "cf9d5b73197a42e411c84f119b36afb30a147430",
          "md5": "9d1ce5da2ced4b34bc5c56a440763268"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kotson-1.0.0-javadoc.jar",
          "url": "kotson-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "c24d598adba30538269e6561b26be181a16fc2140eed6c560d4ef6e5115829ed1c4f22b330035964f05a2d2d4e650041e5ad1595cc0eca535ed0f77f81af203a",
          "sha256": "a4711f5cc727dbf37d35d0ffd27f46f8af2043a2296197dbc9316536a406f77d",
          "sha1": "62182506563aef55ab7db62c1f4ad79c711a172a",
          "md5": "ebdc1675e3acb18b5045040985abdef8"
        }
      ]
    }
  ]
}
