{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nice.kotlins",
    "module": "atomic",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "atomic-1.0.0.jar",
          "url": "atomic-1.0.0.jar",
          "size": 30146,
          "sha512": "df50f122bcfaf8dbf2f2b0f750fa513106d0d07affbe0d26353c2456906f10878c506f0556e25364661f1ece239d445420660a56908f35460fb2fdeddf5a7d97",
          "sha256": "3de9068b877cca9f42718455fdb6341774ca7d43dde1b79c357872861817ffc0",
          "sha1": "8068e88ae55242d2671f66431807c5409c73e91e",
          "md5": "ee859d6f5a0479d1790ede22bc31b7a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "atomic-1.0.0.jar",
          "url": "atomic-1.0.0.jar",
          "size": 30146,
          "sha512": "df50f122bcfaf8dbf2f2b0f750fa513106d0d07affbe0d26353c2456906f10878c506f0556e25364661f1ece239d445420660a56908f35460fb2fdeddf5a7d97",
          "sha256": "3de9068b877cca9f42718455fdb6341774ca7d43dde1b79c357872861817ffc0",
          "sha1": "8068e88ae55242d2671f66431807c5409c73e91e",
          "md5": "ee859d6f5a0479d1790ede22bc31b7a5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "atomic-1.0.0-sources.jar",
          "url": "atomic-1.0.0-sources.jar",
          "size": 5978,
          "sha512": "0080ba8c6c229dc699956d3e2f947868ba1d90f49db5ed076ddc1b863e5e50c07017ec014a81bda5ece6cb46e25bd46237bac5070711d9dbeea72e8a85a4989a",
          "sha256": "c43dc232ca5cd275201e5cc68c58fd4fa6c97568fab91803769401b6c6e8621d",
          "sha1": "153ec72e63b41f44f2333100395c5c089386cf86",
          "md5": "5d3f029b77f441780f889f169d2a4019"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "atomic-1.0.0-javadoc.jar",
          "url": "atomic-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "d8736a8a1e0ffc42fe11e811743b5aab410245d03be48391c249997be4fd004c7b8241dae5d5343fbf8056eaf233a5b5cb51ccc8cf5a37c52e05247e8569a6ff",
          "sha256": "578739222e795e0e1e752eaaa61e4ec2f26517f65d3ea1e596337ac5707ab245",
          "sha1": "0bd2261454fff89639415285d08b21622b5796de",
          "md5": "a359e60579a3a37072a39c82f17736d3"
        }
      ]
    }
  ]
}
