{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nice.kotlins",
    "module": "atomic",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "atomic-1.0.0.jar",
          "url": "atomic-1.0.0.jar",
          "size": 30146,
          "sha512": "9f64dadc25634deb880742e4ac2097df72efe718f705310ffa146b2b16715d7a004f0edd6ebba79afb2f0264ea4dee290113fd4949662fecceea9d8462cbf2c1",
          "sha256": "5650ec71fd62495c9826f6eb5c070c4a124826fdb8813c4fc5e39d1f8b767ec1",
          "sha1": "f2ea939364a72fa2cc843b9578e1874fe3efb823",
          "md5": "a10ce127fc97b6b9dab49d087863c312"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "atomic-1.0.0.jar",
          "url": "atomic-1.0.0.jar",
          "size": 30146,
          "sha512": "9f64dadc25634deb880742e4ac2097df72efe718f705310ffa146b2b16715d7a004f0edd6ebba79afb2f0264ea4dee290113fd4949662fecceea9d8462cbf2c1",
          "sha256": "5650ec71fd62495c9826f6eb5c070c4a124826fdb8813c4fc5e39d1f8b767ec1",
          "sha1": "f2ea939364a72fa2cc843b9578e1874fe3efb823",
          "md5": "a10ce127fc97b6b9dab49d087863c312"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "atomic-1.0.0-sources.jar",
          "url": "atomic-1.0.0-sources.jar",
          "size": 5978,
          "sha512": "73d6c912996c587ab9c643d60b5a9b3e7d3ae7b6648f110b295aabdef1193d2a731289ef05b26d6083eac876a871ed22b65620c2689d5a1eeffb632ee80b46a2",
          "sha256": "fd68f2cc673e92f5e84be693cae9e99404ff7174c2b2ed57cf5c86a2c1ba41c3",
          "sha1": "53f9c788428c3749f7e9da03f4fdc03062202fd6",
          "md5": "4a0e737e2f1bd762e3be5d8146734b34"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "atomic-1.0.0-javadoc.jar",
          "url": "atomic-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "27ac30a0d47edf69e5fd2e136edd367df9ced7159688564a2705e5776fece187701bc4f40d99e335baeba8f0f3f2e2453edd0b5e63af13df918dc2b01a4cca45",
          "sha256": "f0ee91f206419631ddb6a28ea360a9388d5dddc9d610fb860278cfe3f2a49bad",
          "sha1": "a631146909cf8f0e4383997b1b1731fd5ee1e259",
          "md5": "6d6f9aa930e444dc51e43d52a2ddd990"
        }
      ]
    }
  ]
}
