{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nice.kotlins",
    "module": "kot-atomic",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kot-atomic-1.0.0.jar",
          "url": "kot-atomic-1.0.0.jar",
          "size": 30245,
          "sha512": "982a1804f782f2269bfafb3bf40140bfe39b01b2ce137396f238ab3e1239faf4e065a569bd1e8e6c16c5dc8184d46f9e3d79fe2f9016ea37dda74610be9b96f0",
          "sha256": "09364ca5af3160f1388c5ea49d3fdde60fbe145b85941364bad1885bfc7884fb",
          "sha1": "95ccb099dddc092774bfc2498399918d0a8b38fd",
          "md5": "69fc0e0868f9eeaf21cd467e6a518174"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kot-atomic-1.0.0.jar",
          "url": "kot-atomic-1.0.0.jar",
          "size": 30245,
          "sha512": "982a1804f782f2269bfafb3bf40140bfe39b01b2ce137396f238ab3e1239faf4e065a569bd1e8e6c16c5dc8184d46f9e3d79fe2f9016ea37dda74610be9b96f0",
          "sha256": "09364ca5af3160f1388c5ea49d3fdde60fbe145b85941364bad1885bfc7884fb",
          "sha1": "95ccb099dddc092774bfc2498399918d0a8b38fd",
          "md5": "69fc0e0868f9eeaf21cd467e6a518174"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-atomic-1.0.0-sources.jar",
          "url": "kot-atomic-1.0.0-sources.jar",
          "size": 5978,
          "sha512": "36386fb5c964849e10714c77c10e3c52c52a7404ee2edc3f5e805c7c1135003952477820ff9104a36b0f7885bfec974093fd8f6d24666f27f7767d2360daaedf",
          "sha256": "871caf59419ccd4f6dc4985f5ff5c839b89e33bce944fadfcdcee55ff522a63d",
          "sha1": "a78a721cc0de1ba5e65cdf47dc315e443b6234e8",
          "md5": "2f200771a336ab4246a05e85c8a181cf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-atomic-1.0.0-javadoc.jar",
          "url": "kot-atomic-1.0.0-javadoc.jar",
          "size": 261,
          "sha512": "30de81220b729585ea0380baac29ae8af56f63822f33831de31990a0a7630549bef2112eb95096bdfc398a57356fd208bd223f0af63e363dc9f58a9dc2f8746a",
          "sha256": "df5b0122799f14b06d56b1e481d07d4542c3ef5d0e11943e3a37bb3dda1acf24",
          "sha1": "6ed77de24ee41272244b5d44a75306182e0a68b1",
          "md5": "bde2884ff99282c60f00a7a4ec6bf460"
        }
      ]
    }
  ]
}
