{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nice.kotlins",
    "module": "kot-gson",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "kot-gson-1.0.2.jar",
          "url": "kot-gson-1.0.2.jar",
          "size": 215161,
          "sha512": "a3fb7a3fa963ecab969f2fd7c224f35e55dd3d65db4451e071e91b6846ee03f2cae6244b373e5c0f8f446f6ba171592e60a5fe46911a710fe5960bcd4b3292e4",
          "sha256": "640126c409331f0546f5adebe5c13b3de7245a011797ec7584e172846adff70f",
          "sha1": "77117153d51919999e17fa3fe0c7e1566165a58b",
          "md5": "d47831d2db730b1ef2a9841ed1f51928"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "kot-gson-1.0.2.jar",
          "url": "kot-gson-1.0.2.jar",
          "size": 215161,
          "sha512": "a3fb7a3fa963ecab969f2fd7c224f35e55dd3d65db4451e071e91b6846ee03f2cae6244b373e5c0f8f446f6ba171592e60a5fe46911a710fe5960bcd4b3292e4",
          "sha256": "640126c409331f0546f5adebe5c13b3de7245a011797ec7584e172846adff70f",
          "sha1": "77117153d51919999e17fa3fe0c7e1566165a58b",
          "md5": "d47831d2db730b1ef2a9841ed1f51928"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-gson-1.0.2-sources.jar",
          "url": "kot-gson-1.0.2-sources.jar",
          "size": 7848,
          "sha512": "70385e0988ca834b1322582cff506d93870f3cefccd2e43c6df40b5151a6591a41f6d17eda29f60f3903b6ccaff3208c84ae07990ed7840880ea9ab349aca77d",
          "sha256": "204513a6c238dd38019f456be8180684f6803df66c2782c475060abcaac27510",
          "sha1": "7b1fcdcf9a7eefaa6992b0b5bc8d890f354a2a96",
          "md5": "8216ec4f0e663d67bb841f7a2ee4b070"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-gson-1.0.2-javadoc.jar",
          "url": "kot-gson-1.0.2-javadoc.jar",
          "size": 261,
          "sha512": "648bae0aa512f65e8d3eb19f5e9ca6cac4945d61785c4e3f8cfa7a1876afb4d44c923d0dadd94866c645c704a1cce84f5bc6c185050f96fe75f4e9a77a9ad08e",
          "sha256": "872452fae9b564f2545ddf94e9822a3b33e376ab78838211b7607380e0065c5a",
          "sha1": "5142246468aaedf63e6b9760a4c50891b17cd54d",
          "md5": "4d6ac9f99fc460f69ea81a59305bf0f9"
        }
      ]
    }
  ]
}
