{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nice.kotlins",
    "module": "kot-gson",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "kot-gson-1.0.2.jar",
          "url": "kot-gson-1.0.2.jar",
          "size": 215161,
          "sha512": "c3a3af8ce85427e61ac663269b99acab703e231e7dbdeb65a4bf1054366ed2839271e77573a86f03342f3bddcc2674cc99f5b87e50fad32b2ff2b8418b4a54a9",
          "sha256": "6c2a41934051a94b589c7efcf9c2419402efd5a09c06f28bdb39842738d1b065",
          "sha1": "cbb1bc139d5daf12ba203d7e4298f7ba9e6ac5c1",
          "md5": "90c1427ae75727872ab664a18f42a943"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "kot-gson-1.0.2.jar",
          "url": "kot-gson-1.0.2.jar",
          "size": 215161,
          "sha512": "c3a3af8ce85427e61ac663269b99acab703e231e7dbdeb65a4bf1054366ed2839271e77573a86f03342f3bddcc2674cc99f5b87e50fad32b2ff2b8418b4a54a9",
          "sha256": "6c2a41934051a94b589c7efcf9c2419402efd5a09c06f28bdb39842738d1b065",
          "sha1": "cbb1bc139d5daf12ba203d7e4298f7ba9e6ac5c1",
          "md5": "90c1427ae75727872ab664a18f42a943"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-gson-1.0.2-sources.jar",
          "url": "kot-gson-1.0.2-sources.jar",
          "size": 7848,
          "sha512": "3c1c31df3f432cc517c62dff702887ac6116554af66ab26b512a43b451afd7b253174cd7cb4e21d00fd740ad909baa19cc172f7454880956a5e70cbf5bc80151",
          "sha256": "f0af650daecd91094a11a6e25b7bf7f105769be651a59390167d3505a2b1e33d",
          "sha1": "0c0a0ea102e67b611b78fcb2088b91283302883e",
          "md5": "a3bbbc4a0f97078399536a3be47e3dd5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-gson-1.0.2-javadoc.jar",
          "url": "kot-gson-1.0.2-javadoc.jar",
          "size": 261,
          "sha512": "8c8b8d74423d109f9cb67da37156463c414ee98a6316ff1eae96b81c7ac392dac3559e4f9d51e0477dc633503088d5985635a5b536aaeea0c3a3cd01e94d14bc",
          "sha256": "150ce29ec6e6e8466bb31b6e1409ade1e02ec699f57fdeae5949d3f995342f7c",
          "sha1": "d477a217a07a94b98fc72cf16665bd2683ad876b",
          "md5": "bf55b30e2409940c76ecca7725dcb52c"
        }
      ]
    }
  ]
}
