{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nice.kotlins",
    "module": "kot-gson",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "kot-gson-1.0.2.jar",
          "url": "kot-gson-1.0.2.jar",
          "size": 215161,
          "sha512": "14c88c82d69e882bb2a52c10942c12291e26aae16f2e7dc33cedbfc5474af1f4d7402559a2e738d7feb55a23fa85a002aa02f8ab6baf38f56646244e9a6b5289",
          "sha256": "ac2ba54740c49d0feb7c8f8a47a1f4e7cf9f41141db3f8d8f3f7f3c2ab267d3e",
          "sha1": "271765b69ad2b4484a3058c7539591dddb5a4340",
          "md5": "aa71683aff368b7dd0efb57b41b97de1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.9"
          }
        }
      ],
      "files": [
        {
          "name": "kot-gson-1.0.2.jar",
          "url": "kot-gson-1.0.2.jar",
          "size": 215161,
          "sha512": "14c88c82d69e882bb2a52c10942c12291e26aae16f2e7dc33cedbfc5474af1f4d7402559a2e738d7feb55a23fa85a002aa02f8ab6baf38f56646244e9a6b5289",
          "sha256": "ac2ba54740c49d0feb7c8f8a47a1f4e7cf9f41141db3f8d8f3f7f3c2ab267d3e",
          "sha1": "271765b69ad2b4484a3058c7539591dddb5a4340",
          "md5": "aa71683aff368b7dd0efb57b41b97de1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-gson-1.0.2-sources.jar",
          "url": "kot-gson-1.0.2-sources.jar",
          "size": 7910,
          "sha512": "79de394133be6bbb9419a21bc7394b662fd8f088b940f35c92383b14b4eda1fc7e0651a087ddebf0c1f3b26bb1a3516a1bd37b32cd4a6627f76c4476ed4ea766",
          "sha256": "a06f70e1c3cb27a35b52b62fe874c6d6b2cd7774ccf655f5814701ad9879b3c4",
          "sha1": "95b58ecc3dc3e0e9be2d6aae93248cf30c851e99",
          "md5": "edad510cff1f2f026cc5ddc1ee9f3048"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-gson-1.0.2-javadoc.jar",
          "url": "kot-gson-1.0.2-javadoc.jar",
          "size": 261,
          "sha512": "14d9dea429dc6fcaeef3b26c1300beb70ca1fba9f4f75a2db2c0ed443fc1ae1ef16d09c03a38f3e879ec14667d137fc64f65cdd7876f1dab7248eb8d9a642f58",
          "sha256": "6ce5790473e88f81dcc9aa59745009bfd2e19913292a55fb4bcd87835d89e7a2",
          "sha1": "68a145165c9197571484772d220649be16316758",
          "md5": "3abf8132558c572fc49fc4fdff65fce6"
        }
      ]
    }
  ]
}
