{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nice.kotlins",
    "module": "kot-atomic",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kot-atomic-1.0.1.jar",
          "url": "kot-atomic-1.0.1.jar",
          "size": 30242,
          "sha512": "3e145d3d23d955a179b27a23ded799e18ca6c1512abb016e9710a8cd6d28837489d86302f074776f5e1ee7991bcb15370d1a204f6b5d9f291fbdd331f9a3e069",
          "sha256": "9e981be47b1ad2c99a90c4c9adb5fc4eb55bcd57069aa4e084b989bf66e4e07d",
          "sha1": "f5e4c9f2b556230c0460bab1f5fc4d50b6029423",
          "md5": "632ff78770a38beed5ec0ca67e6e8f4d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kot-atomic-1.0.1.jar",
          "url": "kot-atomic-1.0.1.jar",
          "size": 30242,
          "sha512": "3e145d3d23d955a179b27a23ded799e18ca6c1512abb016e9710a8cd6d28837489d86302f074776f5e1ee7991bcb15370d1a204f6b5d9f291fbdd331f9a3e069",
          "sha256": "9e981be47b1ad2c99a90c4c9adb5fc4eb55bcd57069aa4e084b989bf66e4e07d",
          "sha1": "f5e4c9f2b556230c0460bab1f5fc4d50b6029423",
          "md5": "632ff78770a38beed5ec0ca67e6e8f4d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-atomic-1.0.1-sources.jar",
          "url": "kot-atomic-1.0.1-sources.jar",
          "size": 5980,
          "sha512": "a868a3f4df7dc92ea6d2ec05c6b0896f2c8d383d427ab8a4fb5ce384f33462ef4b22fb4cb152bbb628f47d972d9a2d03f84800826b6c06f5a82d16276b59cf13",
          "sha256": "3911f37c44c5653158c88ebcaa621a016b20c6978205b5e675a61ec9426fd3c5",
          "sha1": "1e768637f1e2978aa11b4bec2d6fd755a22b88a8",
          "md5": "a7ad84c30fd0edbf7db4d0322394e1de"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-atomic-1.0.1-javadoc.jar",
          "url": "kot-atomic-1.0.1-javadoc.jar",
          "size": 261,
          "sha512": "60a456d13dfcd7f14138a31b456fbed2d78f131722ddf31a77f5f2af6b3f91452f36cc27d57748462341ab835ad449195baa2321d15f2fce5d73c9a23e5171dc",
          "sha256": "7ed6d354f1af139f502c4cd1a44ab34fbe54c78c7d845386fdbcf3d60feb3372",
          "sha1": "80eb5d4242310d303a3cbf4ba99eae540dce697a",
          "md5": "cf171c01893fdd87fc1922c9f1807e8a"
        }
      ]
    }
  ]
}
