{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nice.kotlins",
    "module": "kot-atomic",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kot-atomic-1.0.1.jar",
          "url": "kot-atomic-1.0.1.jar",
          "size": 30242,
          "sha512": "13720ae5b941d7c0ea8d937ab5bcc034de72dd888d6a7b96fdd6fc340ada9f08929934d11f3e422a1302c010bdbbf8ac1d6cdc814ce28dbed957fafb83f98339",
          "sha256": "8cf20e60746789ba9383b1b3a5722fa81ba23bd09852a3a2b568e933ddc5b7e6",
          "sha1": "7183e4b580dd0319cc259e6256b7400872f46279",
          "md5": "e351bcb66a92d1eea377c478106767f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kot-atomic-1.0.1.jar",
          "url": "kot-atomic-1.0.1.jar",
          "size": 30242,
          "sha512": "13720ae5b941d7c0ea8d937ab5bcc034de72dd888d6a7b96fdd6fc340ada9f08929934d11f3e422a1302c010bdbbf8ac1d6cdc814ce28dbed957fafb83f98339",
          "sha256": "8cf20e60746789ba9383b1b3a5722fa81ba23bd09852a3a2b568e933ddc5b7e6",
          "sha1": "7183e4b580dd0319cc259e6256b7400872f46279",
          "md5": "e351bcb66a92d1eea377c478106767f6"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-atomic-1.0.1-sources.jar",
          "url": "kot-atomic-1.0.1-sources.jar",
          "size": 5980,
          "sha512": "1831dcc958904b6e6c968476c18974598efba1f3f99c19fb707ad458c4c2a8471a7ef40b91de2465af8b8ba6993a860ae550d5c68cfa41e8f315e08125ee964a",
          "sha256": "8db129a6730c67b84e91bddce1bd0b2408841f3c9fdd0cbf6a3b899914694510",
          "sha1": "f18c7d9b96a297d004630818ae1b467fe2f9b12e",
          "md5": "8a6ba027032891fe95474914c2bb4caf"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-atomic-1.0.1-javadoc.jar",
          "url": "kot-atomic-1.0.1-javadoc.jar",
          "size": 261,
          "sha512": "8c0d2b70b092528021e2b3c972dd49d7405eace37a576d4924f7075fe3f1163eb8b7b8400331c1fb8d5df34c2d41811fc046b034b8635f4c0801cd3154c6bc14",
          "sha256": "df816cee76d58d2c30d487f5f3b5e733dd919cb0f65f36e5973ef9ceee58a1b8",
          "sha1": "d96201374b274eb2fe9e9ba770592903fd3a23f1",
          "md5": "a4c72ed8a99ae9741fb07e93ba4646ac"
        }
      ]
    }
  ]
}
