{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nice.kotlins",
    "module": "kot-atomic",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kot-atomic-1.0.1.jar",
          "url": "kot-atomic-1.0.1.jar",
          "size": 30245,
          "sha512": "9cb0a093011ca349f248943d3888cd2760a07ddcf02371508a202cff9744b419bcfd271bca0a84952b70cee7d7a2fec0a691390658d678934e87652267836db9",
          "sha256": "15b0f914dc8a9e94c67c364ae69f7070f24ab6a1f97309f615a349f8fa9b020d",
          "sha1": "293defe75a4ac8fff92488b91709e8bff8b763d0",
          "md5": "91035069f797a3541987c1517462135a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kot-atomic-1.0.1.jar",
          "url": "kot-atomic-1.0.1.jar",
          "size": 30245,
          "sha512": "9cb0a093011ca349f248943d3888cd2760a07ddcf02371508a202cff9744b419bcfd271bca0a84952b70cee7d7a2fec0a691390658d678934e87652267836db9",
          "sha256": "15b0f914dc8a9e94c67c364ae69f7070f24ab6a1f97309f615a349f8fa9b020d",
          "sha1": "293defe75a4ac8fff92488b91709e8bff8b763d0",
          "md5": "91035069f797a3541987c1517462135a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-atomic-1.0.1-sources.jar",
          "url": "kot-atomic-1.0.1-sources.jar",
          "size": 5978,
          "sha512": "7c66c6040f9a5249356587aef39b524a2a5b2c0dceeb782b992d2ea4c4ee8f5c5e75ae4815de2ee967f34f1c8b099e08caf88511f557de83ef374a1035ff6e25",
          "sha256": "34a84c670edcfd543fd7d5e04a783f2ead8e6e794f65b6b77b05e244520c34fc",
          "sha1": "45c256c9213cb1025aa2d18a8a4ddd645c5da431",
          "md5": "0fcd232b998d662044cabdf410a05619"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-atomic-1.0.1-javadoc.jar",
          "url": "kot-atomic-1.0.1-javadoc.jar",
          "size": 261,
          "sha512": "03a3d986aecaafd80d9676f983230bee016a8487bc9f6dd0c21440f2053a8b1931347691c90be2fc28fe20fb6c140e9d248cda3bcafcdba16209a890c176e217",
          "sha256": "e9ae9048ccdfdd96d0a843b27610a30fc01d6b69be3a75e8cd422d9a48b191c8",
          "sha1": "9357881ff3509048f355a0b9fe9113070e214e43",
          "md5": "a99035cddf41bd0d6ab40d963efc7ffd"
        }
      ]
    }
  ]
}
