{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nice.kotlins",
    "module": "kot-atomic",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kot-atomic-1.0.3.jar",
          "url": "kot-atomic-1.0.3.jar",
          "size": 29394,
          "sha512": "0b7676dba1b9ec0a5bfe79060bed1e8fc59c5c199d95f11d97ee0e0188bd4057e199d3f96d4f5c28e1df3b114a377792097a87fdb08c2a0e51adfb0a8c07eb3a",
          "sha256": "338c4c4932cbdd697b2c813ef0f3a29ac96f4dfcadacd6f1425ac9b0eccafc8c",
          "sha1": "0981057a30a43a4a9822e2ca04e1fde1682afcc8",
          "md5": "cceb1f35062982176bde5e583743b3e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kot-atomic-1.0.3.jar",
          "url": "kot-atomic-1.0.3.jar",
          "size": 29394,
          "sha512": "0b7676dba1b9ec0a5bfe79060bed1e8fc59c5c199d95f11d97ee0e0188bd4057e199d3f96d4f5c28e1df3b114a377792097a87fdb08c2a0e51adfb0a8c07eb3a",
          "sha256": "338c4c4932cbdd697b2c813ef0f3a29ac96f4dfcadacd6f1425ac9b0eccafc8c",
          "sha1": "0981057a30a43a4a9822e2ca04e1fde1682afcc8",
          "md5": "cceb1f35062982176bde5e583743b3e1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-atomic-1.0.3-sources.jar",
          "url": "kot-atomic-1.0.3-sources.jar",
          "size": 5942,
          "sha512": "d133b22ae52dac8617b435ac620b9749835a1ddea9bd784c1f5cd7b0faae2c64ff07806b01fc84f8e081674d648bece395a02fe7d820059117433507fbf7d2ed",
          "sha256": "4be751871879b96f5a3cf8b6ba4ba674570897376c6d504f830178aa517bd5d5",
          "sha1": "e5081b35ce654e69260ebf22d61cdbcdbdfde981",
          "md5": "dddc9357641499d66904bb05ddd056d1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-atomic-1.0.3-javadoc.jar",
          "url": "kot-atomic-1.0.3-javadoc.jar",
          "size": 261,
          "sha512": "3d69f5cd0c8acdfaffc826dd9f07f451e33a6c3b4e4851776f992c18814597c8dff25703eb142d449ca01b54a2b10e23b85f6b0cabfc6089614e60311ae371d1",
          "sha256": "f9d7d535f98d5937aeec81154c82bedb570a7705c626fe1d68e145a7e67180a9",
          "sha1": "a44efdbe6bae67b55da842ab86ff824b605a14ff",
          "md5": "66c553414aa7d90a40386dd14dfc5bb4"
        }
      ]
    }
  ]
}
