{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nice.kotlins",
    "module": "kot-gson",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "kot-gson-1.0.1.jar",
          "url": "kot-gson-1.0.1.jar",
          "size": 215161,
          "sha512": "58db036369dc49d69a8b42652a7bca025006d5ba34c628030e746267f2794c48231dd1314aa77d2b72bb08910ec1ebc56328f9507756140c4e8162862675ffdf",
          "sha256": "babf21979e14b0c71ce1c797b3453077c989d7ee2abcb76e8f04ed0791496f31",
          "sha1": "3a0f3928e30c0d0c913cd59ba5b437fe8aadc2f0",
          "md5": "f5b77cb6a5e36bc989478c2927f7b853"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "kot-gson-1.0.1.jar",
          "url": "kot-gson-1.0.1.jar",
          "size": 215161,
          "sha512": "58db036369dc49d69a8b42652a7bca025006d5ba34c628030e746267f2794c48231dd1314aa77d2b72bb08910ec1ebc56328f9507756140c4e8162862675ffdf",
          "sha256": "babf21979e14b0c71ce1c797b3453077c989d7ee2abcb76e8f04ed0791496f31",
          "sha1": "3a0f3928e30c0d0c913cd59ba5b437fe8aadc2f0",
          "md5": "f5b77cb6a5e36bc989478c2927f7b853"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-gson-1.0.1-sources.jar",
          "url": "kot-gson-1.0.1-sources.jar",
          "size": 7848,
          "sha512": "0b53daf638067fd7e1645da508d5e7aec684e393532da7dad6978180c7d30443d940a8407d1f4e160c700279b216472471863044e5f0fdd1f70bcf35fdfe17ee",
          "sha256": "e5773cda37706a817892e6e727670fb6e9650f562fcffd7fe06eaa94c32e343b",
          "sha1": "9f1517b44d00ac36ae5bf75366a4811245ecbea4",
          "md5": "b79358ad593d3b0450377dcb5efbdb21"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-gson-1.0.1-javadoc.jar",
          "url": "kot-gson-1.0.1-javadoc.jar",
          "size": 261,
          "sha512": "0fa483a33c44c29465beb4d55cfff025cf533badb725d2854f194f0c83ff96cbbbbbf158c0d3ee8366eafc1d3bbf8939464225739f66bed17e5bffc1ab8c8582",
          "sha256": "82fe8cc79f39820b3e9bcd73f01802d2856a7df1d553f90016b549be45038759",
          "sha1": "c2eb548a4a9a0f781632c014b871040cb5149883",
          "md5": "d88bd7a29a102e403175a7209e823f3c"
        }
      ]
    }
  ]
}
