{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nice.kotlins",
    "module": "kot-gson",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "kot-gson-1.0.1.jar",
          "url": "kot-gson-1.0.1.jar",
          "size": 215161,
          "sha512": "9622ac1b59f528866f99dcfaf29812e7c50b369468701c26650bfe6414d787ce6bb7804a8aa9693ecb615bc5e4f1bf9d8d526338da9e0c816e886d8cf7f08817",
          "sha256": "9a78891ae0eaf255845d3ab5b0773f3b6f40d501d9d4ea8cdf00f8d6a2fac740",
          "sha1": "5bc34e955b909b0a329f27be83353e2bb490d0db",
          "md5": "ea74536150b1c186d6ab6daa317787a1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "kot-gson-1.0.1.jar",
          "url": "kot-gson-1.0.1.jar",
          "size": 215161,
          "sha512": "9622ac1b59f528866f99dcfaf29812e7c50b369468701c26650bfe6414d787ce6bb7804a8aa9693ecb615bc5e4f1bf9d8d526338da9e0c816e886d8cf7f08817",
          "sha256": "9a78891ae0eaf255845d3ab5b0773f3b6f40d501d9d4ea8cdf00f8d6a2fac740",
          "sha1": "5bc34e955b909b0a329f27be83353e2bb490d0db",
          "md5": "ea74536150b1c186d6ab6daa317787a1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-gson-1.0.1-sources.jar",
          "url": "kot-gson-1.0.1-sources.jar",
          "size": 7842,
          "sha512": "401b67c902443736f26d7e347d5802175c6c31e1d8d7da19531529c4466f45f965fc179c4dbef0c7e3bc3e5c53c234f89a3f1986137f7adb97f154cb2ee141f8",
          "sha256": "4563845bd2a66f0889aeb431335b9935452b33b94ba271d3130caf3e502482c5",
          "sha1": "d763b699ed180bff8ea7b36fd32ebfd74648e608",
          "md5": "d98cbe0b63516bd8d1f7805c8701bbcd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-gson-1.0.1-javadoc.jar",
          "url": "kot-gson-1.0.1-javadoc.jar",
          "size": 261,
          "sha512": "5d63ba27b6f095955a370abea53e824e411bbdec0091c47b01915dc2908b116b864e98482722f9a93b05c94453dfdc42701c58c4a93b71767b6860f0ba40f3c5",
          "sha256": "80d20133965b87b1eaf349d45238b617b09a60eabf259743ca622ef0abd2a114",
          "sha1": "08c3e0aaba997d43d4bb41006d3b944af7cfd522",
          "md5": "2785b6bd228a3055ddcbd85135114ce9"
        }
      ]
    }
  ]
}
