{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nice.kotlins",
    "module": "kot-gson",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "kot-gson-1.0.1.jar",
          "url": "kot-gson-1.0.1.jar",
          "size": 214768,
          "sha512": "006354c499b93e4a63ef93ef47ecdf44a39c30d6efe3e95bfade1f0a4b1d113ec50874368f50be6d98fc2ffc6bda2f4f8a2498ec64201151a24c98aac71bdd4c",
          "sha256": "5f40fac4affe7211b6482e34377308585fe7e2b5daadd1a818200b2d4c99a36f",
          "sha1": "5adad22269eec9d9b6ffd08bcd4c67aaa85599c6",
          "md5": "b84859def7c7a20d9acb9277eefa88df"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        }
      ],
      "files": [
        {
          "name": "kot-gson-1.0.1.jar",
          "url": "kot-gson-1.0.1.jar",
          "size": 214768,
          "sha512": "006354c499b93e4a63ef93ef47ecdf44a39c30d6efe3e95bfade1f0a4b1d113ec50874368f50be6d98fc2ffc6bda2f4f8a2498ec64201151a24c98aac71bdd4c",
          "sha256": "5f40fac4affe7211b6482e34377308585fe7e2b5daadd1a818200b2d4c99a36f",
          "sha1": "5adad22269eec9d9b6ffd08bcd4c67aaa85599c6",
          "md5": "b84859def7c7a20d9acb9277eefa88df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-gson-1.0.1-sources.jar",
          "url": "kot-gson-1.0.1-sources.jar",
          "size": 7842,
          "sha512": "96ea28461ad572eb5d1b4f55dce0afddeea3e731790bfaab17a97837783507321b404a019fc37687788691e6b3e1edcf825d620fa5d5c2d679d64327541e2e6f",
          "sha256": "3530ee00b4d78f2cf5c8a0fd5d33575b59e03fc4da6877ab7229556766f947b1",
          "sha1": "2c7e81f2cd11fd2901fd943f6afcdbd869109d0e",
          "md5": "2ecb724a348411fd3030ede16f1a8266"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-gson-1.0.1-javadoc.jar",
          "url": "kot-gson-1.0.1-javadoc.jar",
          "size": 261,
          "sha512": "9598a294c1b181f230ed993fa7faf8dc821e0f1589fffd7968ed38cb66bcdd6874ca33730ca848912320c6d17a9df5766daa6687c2fe592e9480589d5e97ae1f",
          "sha256": "f4c37f3609b6575f7cd2e78ff2c4e4a99150602b7c7580ee29cf9cdccea39ecf",
          "sha1": "cb1c36845208d0758b64b6b5f70393291803a0ff",
          "md5": "de227f19897ff3593209ae2aac7f6ab0"
        }
      ]
    }
  ]
}
