{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nice.kotlins",
    "module": "kot-atomic",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3-rc-1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kot-atomic-1.0.2.jar",
          "url": "kot-atomic-1.0.2.jar",
          "size": 30288,
          "sha512": "cd00e391eed49ec6d51f8beb60f6f13bac53473f102d52800d804c16ecfc28034837612d99f7ce291b64d6727abb0c8aad35b10f7ab5a9cc942459c4218a0425",
          "sha256": "33e42b3d5a5929fa19a2b3d00b2a6691706090db386618764adcbbc2a7f307a2",
          "sha1": "faaee551bb5a150612c04f84c7e36c801e625e19",
          "md5": "d97959b6f171e20dd8a72b2f1d770d4b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kot-atomic-1.0.2.jar",
          "url": "kot-atomic-1.0.2.jar",
          "size": 30288,
          "sha512": "cd00e391eed49ec6d51f8beb60f6f13bac53473f102d52800d804c16ecfc28034837612d99f7ce291b64d6727abb0c8aad35b10f7ab5a9cc942459c4218a0425",
          "sha256": "33e42b3d5a5929fa19a2b3d00b2a6691706090db386618764adcbbc2a7f307a2",
          "sha1": "faaee551bb5a150612c04f84c7e36c801e625e19",
          "md5": "d97959b6f171e20dd8a72b2f1d770d4b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-atomic-1.0.2-sources.jar",
          "url": "kot-atomic-1.0.2-sources.jar",
          "size": 6034,
          "sha512": "7525f0db3646a62b721b07250e09fc777836a0ac6d427167ca4ea6f0d40d485a3cbc278879d6ae387cf9deb4bb55d5c81ca60e0949f669ab8f65c3745596517c",
          "sha256": "840451db24ad8fb13709f8ab3a225d04fd8e588584a2f9ad08618e7ab48cfc87",
          "sha1": "7280940e5c102a328d1317eceeac0cc19fe81a14",
          "md5": "6e56856f4e5bb3dd571dbc759ee717f4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-atomic-1.0.2-javadoc.jar",
          "url": "kot-atomic-1.0.2-javadoc.jar",
          "size": 261,
          "sha512": "fc3030ed65f923fe628d18eb656c4dbf4e07d1728c319d1e765aac57a92e96c1e8208bb3df1849dcc36a798353530b4ecb509f76a815f34e3979dc6143a8ef00",
          "sha256": "913298c80f46879a28e1c36a79a645f0de46d920915ea73d75cf087883a8bf4a",
          "sha1": "de8ee41818ae5a98522fa6b516169305ed04b3bb",
          "md5": "7ec27312962278523fca63201c436602"
        }
      ]
    }
  ]
}
