{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nice.kotlins",
    "module": "kot-atomic",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kot-atomic-1.0.2.jar",
          "url": "kot-atomic-1.0.2.jar",
          "size": 29400,
          "sha512": "28ff4f4377b3dffef6b0dbcd2f926959b5abe93400679ab4c97cf8608399f501980d0f7f3cc81682c1f546cfbe1a41837098f4f0f484422090032552c25914e6",
          "sha256": "da7c62c48425677b241496209daf9a7db9d458ae8866550733e1358d429b93d7",
          "sha1": "2ffc16f54ee59c3df23f091913cf724e81949f10",
          "md5": "82636fcdaa4981df6275964c22d15d2f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "kot-atomic-1.0.2.jar",
          "url": "kot-atomic-1.0.2.jar",
          "size": 29400,
          "sha512": "28ff4f4377b3dffef6b0dbcd2f926959b5abe93400679ab4c97cf8608399f501980d0f7f3cc81682c1f546cfbe1a41837098f4f0f484422090032552c25914e6",
          "sha256": "da7c62c48425677b241496209daf9a7db9d458ae8866550733e1358d429b93d7",
          "sha1": "2ffc16f54ee59c3df23f091913cf724e81949f10",
          "md5": "82636fcdaa4981df6275964c22d15d2f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-atomic-1.0.2-sources.jar",
          "url": "kot-atomic-1.0.2-sources.jar",
          "size": 5942,
          "sha512": "6f1ab05d13c1f57f76b6f88f29ffff85f1ff73a2198738a51af7d26a8c3420617b96bf385a5facf096bfbb836522186787e449f93b03fbcfccae5fda96017102",
          "sha256": "a716eeb27e7f8d6b32c508a099a54b0f76f441ffc9e32e2d0667547897bcfbc8",
          "sha1": "eadd749835806e9fff34bb48b6634a8b0188aa74",
          "md5": "567e3bf7d235dfe840f52a5a70aea166"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-atomic-1.0.2-javadoc.jar",
          "url": "kot-atomic-1.0.2-javadoc.jar",
          "size": 261,
          "sha512": "f474b25c2f1bf8cf2ebdcfc2088ce4c1ca67a3b20e085183da8b2f006f4bc92d5680098fdebcec052232bf51199fbb78d0e267350ca6ee100e456c258a0acf99",
          "sha256": "3674823325b13ee8206c6ab6a3413c0e8df5a73e38c648e0c533cbcadc6b4ccd",
          "sha1": "58a9311948983573b6a55bbb9502af73bcc45745",
          "md5": "53889f4b5316cc73d5cedddbbf325d7b"
        }
      ]
    }
  ]
}
