{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nice.kotlins",
    "module": "kot-atomic",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kot-atomic-1.0.2.jar",
          "url": "kot-atomic-1.0.2.jar",
          "size": 29333,
          "sha512": "37db09b2d8677ea92d6aaa6e4061115f953d14b6438018362909932fffad6ea612db443139069f9e42821190f07acae7f01fa37c911b289b4ad24c27566c154d",
          "sha256": "d539a3c6b02394a9b7e3ef9f12c4f871c204bf4fd03e98d0067f4698b270e986",
          "sha1": "c40b8c983adfe8fc130377c6d70f02fa37bb9e13",
          "md5": "b259bbd86514bc67dadb9a97510a587f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.31"
          }
        }
      ],
      "files": [
        {
          "name": "kot-atomic-1.0.2.jar",
          "url": "kot-atomic-1.0.2.jar",
          "size": 29333,
          "sha512": "37db09b2d8677ea92d6aaa6e4061115f953d14b6438018362909932fffad6ea612db443139069f9e42821190f07acae7f01fa37c911b289b4ad24c27566c154d",
          "sha256": "d539a3c6b02394a9b7e3ef9f12c4f871c204bf4fd03e98d0067f4698b270e986",
          "sha1": "c40b8c983adfe8fc130377c6d70f02fa37bb9e13",
          "md5": "b259bbd86514bc67dadb9a97510a587f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-atomic-1.0.2-sources.jar",
          "url": "kot-atomic-1.0.2-sources.jar",
          "size": 5942,
          "sha512": "6f1ab05d13c1f57f76b6f88f29ffff85f1ff73a2198738a51af7d26a8c3420617b96bf385a5facf096bfbb836522186787e449f93b03fbcfccae5fda96017102",
          "sha256": "a716eeb27e7f8d6b32c508a099a54b0f76f441ffc9e32e2d0667547897bcfbc8",
          "sha1": "eadd749835806e9fff34bb48b6634a8b0188aa74",
          "md5": "567e3bf7d235dfe840f52a5a70aea166"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "kot-atomic-1.0.2-javadoc.jar",
          "url": "kot-atomic-1.0.2-javadoc.jar",
          "size": 261,
          "sha512": "f474b25c2f1bf8cf2ebdcfc2088ce4c1ca67a3b20e085183da8b2f006f4bc92d5680098fdebcec052232bf51199fbb78d0e267350ca6ee100e456c258a0acf99",
          "sha256": "3674823325b13ee8206c6ab6a3413c0e8df5a73e38c648e0c533cbcadc6b4ccd",
          "sha1": "58a9311948983573b6a55bbb9502af73bcc45745",
          "md5": "53889f4b5316cc73d5cedddbbf325d7b"
        }
      ]
    }
  ]
}
